#server:
#  port: 8071

spring:
  application:
    name: gateway-server
  config:
    activate:
      on-profile: default
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - name: AuthGlobalFilter
          args:
            message: Spring Gateway Auth Filter
            authCheck: true
        - name: LoggingGlobalFilter
          args:
            message: Spring Gateway Logging Filter
            preLogger: true
            postLogger: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true

kafka:
  clusters:
    bootstrapservers: localhost:9092

---

spring:
  application:
    name: gateway-server
  config:
    activate:
      on-profile: docker
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - name: AuthGlobalFilter
          args:
            message: Spring Gateway Auth Filter
            authCheck: true
        - name: LoggingGlobalFilter
          args:
            message: Spring Gateway Logging Filter
            preLogger: true
            postLogger: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true

kafka:
  clusters:
    bootstrapservers: lucycato-kafka:9092