server:
  port: 9090

spring:
  application:
    name: gateway-server
  config:
    import: application-common.yml
    activate:
      on-profile: default
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - name: AuthGlobalFilter
          args:
            message: Spring Gateway Auth Filter
        - name: LoggingGlobalFilter
          args:
            message: Spring Gateway Logging Filter
      routes:
        - id: user-auth-command-service
          uri: lb://user-auth-command-service
          predicates:
            - Path=/user-auth-command/**
          filters:
            - RewritePath=/user-auth-command/(?<segment>.*), /${segment}
        - id: user-auth-query-service
          uri: lb://user-auth-query-service
          predicates:
            - Path=/user-auth-query/**
          filters:
            - RewritePath=/user-auth-query/(?<segment>.*), /${segment}
        - id: notification-command-service
          uri: lb://notification-command-service
          predicates:
            - Path=/notification-command/**
          filters:
            - RewritePath=/notification-command/(?<segment>.*), /${segment}
        - id: notification-query-service
          uri: lb://notification-query-service
          predicates:
            - Path=/notification-query/**
          filters:
            - RewritePath=/notification-query/(?<segment>.*), /${segment}
        - id: product-command-service
          uri: lb://product-command-service
          predicates:
            - Path=/product-command/**
          filters:
            - RewritePath=/product-command/(?<segment>.*), /${segment}
        - id: product-query-service
          uri: lb://product-query-service
          predicates:
            - Path=/product-query/**
          filters:
            - RewritePath=/product-query/(?<segment>.*), /${segment}
        - id: board-command-service
          uri: lb://board-command-service
          predicates:
            - Path=/board-command/**
          filters:
            - RewritePath=/board-command/(?<segment>.*), /${segment}
        - id: board-query-service
          uri: lb://board-query-service
          predicates:
            - Path=/board-query/**
          filters:
            - RewritePath=/board-query/(?<segment>.*), /${segment}
        - id: event-command-service
          uri: lb://event-command-service
          predicates:
            - Path=/event-command/**
          filters:
            - RewritePath=/event-command/(?<segment>.*), /${segment}
        - id: event-query-service
          uri: lb://event-query-service
          predicates:
            - Path=/event-query/**
          filters:
            - RewritePath=/event-query/(?<segment>.*), /${segment}
        - id: order-command-service
          uri: lb://order-command-service
          predicates:
            - Path=/order-command/**
          filters:
            - RewritePath=/order-command/(?<segment>.*), /${segment}
        - id: order-query-service
          uri: lb://order-query-service
          predicates:
            - Path=/order-query/**
          filters:
            - RewritePath=/order-query/(?<segment>.*), /${segment}


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

kafka:
  clusters:
    bootstrapservers: localhost:9092

---

spring:
  application:
    name: gateway-server
  config:
    import: application-common.yml
    activate:
      on-profile: docker
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - name: AuthGlobalFilter
          args:
            message: Spring Gateway Auth Filter
            authCheck: true
        - name: LoggingGlobalFilter
          args:
            message: Spring Gateway Logging Filter
            preLogger: true
            postLogger: true
      routes:
        - id: user-auth-command-service
          uri: lb://user-auth-command-service
          predicates:
            - Path=/user-auth-command/**
          filters:
            - RewritePath=/user-auth-command/(?<segment>.*), /${segment}
        - id: user-auth-query-service
          uri: lb://user-auth-query-service
          predicates:
            - Path=/user-auth-query/**
          filters:
            - RewritePath=/user-auth-query/(?<segment>.*), /${segment}
        - id: notification-command-service
          uri: lb://notification-command-service
          predicates:
            - Path=/notification-command/**
          filters:
            - RewritePath=/notification-command/(?<segment>.*), /${segment}
        - id: notification-query-service
          uri: lb://notification-query-service
          predicates:
            - Path=/notification-query/**
          filters:
            - RewritePath=/notification-query/(?<segment>.*), /${segment}
        - id: product-command-service
          uri: lb://product-command-service
          predicates:
            - Path=/product-command/**
          filters:
            - RewritePath=/product-command/(?<segment>.*), /${segment}
        - id: product-query-service
          uri: lb://product-query-service
          predicates:
            - Path=/product-query/**
          filters:
            - RewritePath=/product-query/(?<segment>.*), /${segment}
        - id: board-command-service
          uri: lb://board-command-service
          predicates:
            - Path=/board-command/**
          filters:
            - RewritePath=/board-command/(?<segment>.*), /${segment}
        - id: board-query-service
          uri: lb://board-query-service
          predicates:
            - Path=/board-query/**
          filters:
            - RewritePath=/board-query/(?<segment>.*), /${segment}
        - id: event-command-service
          uri: lb://event-command-service
          predicates:
            - Path=/event-command/**
          filters:
            - RewritePath=/event-command/(?<segment>.*), /${segment}
        - id: event-query-service
          uri: lb://event-query-service
          predicates:
            - Path=/event-query/**
          filters:
            - RewritePath=/event-query/(?<segment>.*), /${segment}
        - id: order-command-service
          uri: lb://order-command-service
          predicates:
            - Path=/order-command/**
          filters:
            - RewritePath=/order-command/(?<segment>.*), /${segment}
        - id: order-query-service
          uri: lb://order-query-service
          predicates:
            - Path=/order-query/**
          filters:
            - RewritePath=/order-query/(?<segment>.*), /${segment}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

kafka:
  clusters:
    bootstrapservers: lucycato-kafka:9092

springdoc:
  enable-native-support: true
  version: v1
  packages-to-scan: org.lucycato
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger-ui.html            # Swagger UI 경로 => localhost:8081/swagger-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    doc-expansion: none
    urls[0]:
      name: user-auth-command 서비스
      url: http://localhost:9090/user-auth-command/api-docs/json
    urls[1]:
      name: user-auth-query 서비스
      url: http://localhost:9090/user-auth-query/api-docs/json
    urls[2]:
      name: notification-command 서비스
      url: http://localhost:9090/notification-command/api-docs/json
    urls[3]:
      name: notification-query 서비스
      url: http://localhost:9090/notification-query/api-docs/json
    urls[4]:
      name: product-command 서비스
      url: http://localhost:9090/product-command/api-docs/json
    urls[5]:
      name: product-query 서비스
      url: http://localhost:9090/product-query/api-docs/json
    urls[6]:
      name: board-command 서비스
      url: http://localhost:9090/board-command/api-docs/json
    urls[7]:
      name: board-query 서비스
      url: http://localhost:9090/board-query/api-docs/json
    urls[8]:
      name: event-command 서비스
      url: http://localhost:9090/event-command/api-docs/json
    urls[9]:
      name: event-query 서비스
      url: http://localhost:9090/event-query/api-docs/json
    urls[10]:
      name: order-command 서비스
      url: http://localhost:9090/order-command/api-docs/json
    urls[11]:
      name: order-query 서비스
      url: http://localhost:9090/order-query/api-docs/json


  api-docs:
    enabled: true
    path: /api-docs/json
  cache:
    disabled: true
