version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    networks:
      - lucycato_network
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=default
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - TZ=Asia/Seoul
    command: [
      '--default-authentication-plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_general_ci',
      '--lower_case_table_names=1'
    ]
    volumes:
      - ./data/mysql:/data

  redis:
    container_name: redis
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    networks:
      - lucycato_network
  
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=mydatabase
      - MONGO_INITDB_USERNAME=user
      - MONGO_INITDB_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - registry-net

networks:
  lucycato_network:
    driver: bridge
