version: "3.8"

services:
  lucycato-mysql:
    container_name: lucycato-mysql
    image: mysql:8.0.29
    networks:
      - "lucycato_network"
    user: 1000:1000
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=default
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - TZ=Asia/Seoul
    ports:
      - "23306:3306"
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_general_ci',
      '--lower_case_table_names=1'
    ]

#  lucycato-phpmyadmin:
#    container_name: lucycato-phpmyadmin
#    image: phpmyadmin/phpmyadmin:5.0.4
#    depends_on:
#      - lucycato-mysql
#    environment:
#      - PMA_HOST=lucycato-mysql
#      - MYSQL_ROOT_PASSWORD=password
#    ports:
#      - "20080:80"
#    networks:
#      - "lucycato_network"

  lucycato-redis:
    container_name: lucycato-redis
    image: redis:latest
    command: redis-server
    ports:
      - "26379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - "lucycato_network"


  lucycato-zookeeper:
    container_name: lucycato-zookeeper
    image: zookeeper:3.9.2
    networks:
      - "lucycato_network"
    ports:
      - '22181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_TLS_CLIENT_AUTH=none
      - ZOO_TLS_QUORUM_CLIENT_AUTH=none

  lucycato-kafka:
    container_name: lucycato-kafka
    image: bitnami/kafka:latest
    networks:
      - "lucycato_network"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@lucycato-kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    depends_on:
      - lucycato-zookeeper

#  lucycato-kafka-ui:
#    container_name: lucycato-kafka-ui
#    image: provectuslabs/kafka-ui
#    networks:
#      - "lucycato_network"
#    ports:
#      - "28989:8080"
#    depends_on:
#      - lucycato-kafka
#      - lucycato-zookeeper
#    environment:
#      - KAFKA_CLUSTERS_0_NAME=local
#      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=lucycato-lucycato-kafka:9092
#      - KAFKA_CLUSTERS_0_ZOOKEEPER=lucycato-zookeeper:2181

networks:
  lucycato_network:
    driver: bridge
