version: "3.8"
services:
  user-service:
    image: lucycato/lucycato-e-commerce-user-service:1.0.0
    networks:
      - "lucycato_network"
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/default
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL-AUTO=create
      - SPRING_JPA_SHOW-SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
  notification-service:
    image: lucycato/lucycato-e-commerce-notification-service:1.0.0
    networks:
      - "lucycato_network"
    ports:
      - "8081:8080"
  product-service:
    image: lucycato/lucycato-e-commerce-product-service:1.0.0
    networks:
      - "lucycato_network"
    ports:
      - "8082:8080"
    environment:
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - SPRING_R2DBC_URL=r2dbc:mysql://mysql:3306/default
      - SPRING_R2DBC_USERNAME=admin
      - SPRING_R2DBC_PASSWORD=password

networks:
  lucycato_network:
    driver: bridge