services:
  prometheus:
    image: prom/prometheus:latest
    container_name: lucycato-prometheus
    ports:
      - "39090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      custom_network:
        ipv4_address: 172.20.0.4

  loki:
    container_name: lucycato-loki
    image: grafana/loki:latest
    ports:
      - "33100:3100"
    volumes:
      - ./data/loki-data:/loki
      - ./data/loki-rules:/tmp/loki/rules
      - ./data/loki-chunks:/tmp/loki/chunks
      - ./loki-config.yaml:/mnt/config/loki-config.yaml
    command: -config.file=/mnt/config/loki-config.yaml
    networks:
      custom_network:
        ipv4_address: 172.20.0.5
    user: root # 권한 문제를 해결하기 위해 루트 사용자로 실행

  grafana:
    container_name: lucycato-grafana
    image: grafana/grafana:latest
    ports:
      - "33000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      custom_network:
        ipv4_address: 172.20.0.6

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      custom_network:
        ipv4_address: 172.20.0.32

  # node_exporter:
  #   image: quay.io/prometheus/node-exporter:latest
  #   container_name: lucycato-node_exporter
  #   command:
  #     - '--path.rootfs=/host'
  #   pid: host
  #   restart: unless-stopped
  #   volumes:
  #     - '/:/host:ro,rslave'
  #   networks:
  #     custom_network:
  #       ipv4_address: 172.20.0.32

  cadvisor:
    container_name: lucycato-cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    privileged: true
    devices:
      - "/dev/kmsg"
    networks:
      custom_network:
        ipv4_address: 172.20.0.31

networks:
  custom_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16