services:
  lucycato-mysql:
    container_name: lucycato-mysql
    image: mysql:8.0.29
    networks:
      custom_network:
        ipv4_address: 172.20.0.8
    user: 1000:1000
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=default
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - TZ=Asia/Seoul
    ports:
      - "23306:3306"
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_general_ci',
      '--lower_case_table_names=1'
    ]

  lucycato-phpmyadmin:
    container_name: lucycato-phpmyadmin
    image: phpmyadmin/phpmyadmin:5.0.4
    depends_on:
      - lucycato-mysql
    environment:
      - PMA_HOST=lucycato-mysql
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "20080:80"
    networks:
      custom_network:
        ipv4_address: 172.20.0.69

  lucycato-redis:
    container_name: lucycato-redis
    image: redis:latest
    command: redis-server
    ports:
      - "26379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      custom_network:
        ipv4_address: 172.20.0.9

  lucycato-zookeeper:
    container_name: lucycato-zookeeper
    image: zookeeper:3.9.2
    networks:
      custom_network:
        ipv4_address: 172.20.0.10
    ports:
      - '22181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_TLS_CLIENT_AUTH=none
      - ZOO_TLS_QUORUM_CLIENT_AUTH=none

  lucycato-kafka:
    container_name: lucycato-kafka
    image: bitnami/kafka:latest
    networks:
      custom_network:
        ipv4_address: 172.20.0.11
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@lucycato-kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    depends_on:
      - lucycato-zookeeper

networks:
  custom_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
