version: "3.8"
services:
  gateway-server:
    image: lucycato/lucycato-e-commerce-gateway-server:1.0.0
    networks:
      - "lucycato_network"
    ports:
      - "8060:8080"
    environment:
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=lucycato-kafka:9092
  eureka-server:
    image: lucycato/lucycato-e-commerce-eureka-server:1.0.0
    networks:
      - "lucycato_network"
    ports:
      - "8062:8080"

networks:
  lucycato_network:
    driver: bridge