server:
  port: 8083

spring:
  application:
    name: notification-query-service
  config:
    activate:
      on-profile: default
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true

kafka:
  clusters:
    bootstrapservers: localhost:9092


---

spring:
  application:
    name: notification-query-service
  config:
    activate:
      on-profile: docker
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true

kafka:
  clusters:
    bootstrapservers: lucycato-kafka:9092