server:
  port: 8083

spring:
  application:
    name: notification-query-service
  config:
    import: application-common.yml
    activate:
      on-profile: default
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

kafka:
  clusters:
    bootstrapservers: localhost:9092


---
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "metrics, health, info, prometheus"
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    metrics: 
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true

spring:
  application:
    name: notification-query-service
  config:
    import: application-common.yml
    activate:
      on-profile: docker
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

kafka:
  clusters:
    bootstrapservers: lucycato-kafka:9092