server:
  port: 8085

spring:
  application:
    name: product-query-service
  config:
    import: application-common.yml
    activate:
      on-profile: default
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  r2dbc:
    url: r2dbc:mysql://localhost:3306/product_service
    username: admin
    password: password
  data:
    redis:
      host: localhost
      port: 26379

logging:
  level:
    org.springframework.r2dbc.core: debug

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

kafka:
  clusters:
    bootstrapservers: localhost:9092

---

spring:
  application:
    name: product-query-service
  config:
    import: application-common.yml
    activate:
      on-profile: docker
  r2dbc:
    url: r2dbc:mysql://lucycato-mysql:3306/product_service
    username: admin
    password: password
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  data:
    redis:
      host: lucycato-redis
      port: 6379

logging:
  level:
    org.springframework.r2dbc.core: debug

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

kafka:
  clusters:
    bootstrapservers: lucycato-kafka:9092