server:
  port: 8085

spring:
  application:
    name: product-query-service
  config:
    import: application-common.yml
    activate:
      on-profile: default
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

  r2dbc:
    url: r2dbc:mysql://localhost:3306/default
    username: admin
    password: password

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true

kafka:
  clusters:
    bootstrapservers: localhost:9092

---

spring:
  application:
    name: product-query-service
  config:
    import: application-common.yml
    activate:
      on-profile: docker
  r2dbc:
    url: r2dbc:mysql://lucycato-mysql:3306/default
    username: admin
    password: password
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true

kafka:
  clusters:
    bootstrapservers: lucycato-kafka:9092