#spring.application.name=order-query-service
spring:
  config:
    activate:
      on-profile: default

server:
  port: 8091

kafka:
  clusters:
    bootstrapservers: localhost:9092


---

spring:
  config:
    activate:
      on-profile: docker


kafka:
  clusters:
    bootstrapservers: lucycato-kafka:9092