server:
  port: 8090

spring:
  application:
    name: order-command-service
  config:
    activate:
      on-profile: default
  data:
    redis:
      host: localhost
      port: 26379

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true

kafka:
  clusters:
    bootstrapservers: localhost:9092


---

spring:
  application:
    name: order-command-service
  config:
    activate:
      on-profile: docker
  data:
    redis:
      host: lucycato-redis
      port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true

kafka:
  clusters:
    bootstrapservers: lucycato-kafka:9092