spring:
  config:
    activate:
      on-profile: default

server:
  port: 8081


kafka:
  clusters:
    bootstrapservers: localhost:9092


---

spring:
  config:
    activate:
      on-profile: prod


kafka:
  clusters:
    bootstrapservers: lucycato-kafka:9092
