server:
  port: 8088

spring:
  application:
    name: user-course-command-service
  config:
    import: application-common.yml
    activate:
      on-profile: default
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

  r2dbc:
    url: r2dbc:mysql://localhost:23306/default
    username: admin
    password: password

kafka:
  clusters:
    bootstrapservers: localhost:9092

---

spring:
  application:
    name: user-course-command-service
  config:
    import: application-common.yml
    activate:
      on-profile: docker
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

  r2dbc:
    url: r2dbc:mysql://mysql:3306/default
    username: admin
    password: password

kafka:
  clusters:
    bootstrapservers: lucycato-kafka:9092