server:
  port: 8088

spring:
  application:
    name: user-course-command-service
  config:
    import: application-common.yml
    activate:
      on-profile: default
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  r2dbc:
    url: r2dbc:mysql://localhost:3306/default
    username: admin
    password: password
  data:
    redis:
      host: localhost
      port: 26379

logging:
  level:
    org.springframework.r2dbc.core: debug

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

kafka:
  clusters:
    bootstrapservers: localhost:9092

---
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "metrics, health, info, prometheus"
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    metrics: 
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true

spring:
  application:
    name: user-course-command-service
  config:
    import: application-common.yml
    activate:
      on-profile: docker
  r2dbc:
    url: r2dbc:mysql://lucycato-mysql:3306/default
    username: admin
    password: password
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  data:
    redis:
      host: lucycato-redis
      port: 6379

logging:
  level:
    org.springframework.r2dbc.core: debug

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

kafka:
  clusters:
    bootstrapservers: lucycato-kafka:9092