server:
  port: 8080

spring:
  application:
    name: user-auth-command-service
  config:
    import: application-common.yml
    activate:
      on-profile: default
  datasource:
    url: jdbc:mysql://localhost:23306/default
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 26379
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

kafka:
  clusters:
    bootstrapservers: localhost:9092

---

spring:
  application:
    name: user-auth-command-service
  config:
    import: application-common.yml
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://lucycato-mysql:3306/default
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: lucycato-redis
      port: 6379
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

kafka:
  clusters:
    bootstrapservers: lucycato-kafka:9092

---

spring:
  application:
    name: user-auth-command-service
  config:
    import: application-common.yml
    activate:
      on-profile: service_local_db_server
  datasource:
    url: jdbc:mysql://hometo.store:23306/default
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: hometo.store
      port: 26379
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://hometo.store:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

kafka:
  clusters:
    bootstrapservers: hometo.store:9092